server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_demo
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  application:
    name: user-service
mybatis:
  type-aliases-package: com.sth.user.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1