server:
  port: 10010
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
#zuul最原始的配置
zuul:
  routes:
#    # 原始配置
#    user-service:
#      path: /user-service/**
#      serviceId: user-service
#    #去除前缀
#    strip-prefix: false
    #简化配置 这个为默认配置所有不配就可以
    user-service: /user-service/**
  #忽略服务配置，只允许服务间的调用
  ignored-services:
    - consumer-service